### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'merge'

### ISSUE THREAD

**Issue by seanfarley** [mission-liao/pyswagger#51] opened 2015-12-11 23:46 UTC
I'm attempting to use `pyswagger` with http://api.bitbucket.org/swagger.json but can't get it to parse since it raises this error. It seems to be in `AdditionalPropertiesContext.produce`. The `self._obj` variable is set to an empty dictionary `{}` so the comparison to `None` is false:

```python
def produce(self):
    if self._obj:
        return self._obj
    else:
        return AdditionalPropertiesContext._TmpObj(self)
```

I don't know the code well enough to say what it should be returning here. Any thoughts?

**Comment by mission-liao** [comment] 2015-12-12 01:43
Hi, I found where the problem is. "additionalProperties" can have either type of values:
 - boolean
 - Schema Object

In short, pyswagger did something to workaround this special case by providing a customized constructor for its parsing-context, which has a produce method:
```python
   def produce(self):
      if self._obj != None:
          // we should already have a Schame Object inside...
          return self._obj                                                                                              
      else:                                                                                                             
          return AdditionalPropertiesContext._TmpObj(self) 
```

The right way here is checking both None and {}.

follow-up:
 - I will fix this bug and add a small test case.
 - the swagger.json of bitbucket is the biggest one I've seen, I will create a test case to make sure its loading would be fine. other uses cases should also be included, but not this time.

It will take me sometime to finish it (half a day I guess), before that, you can correct it by patching it
  pyswagger.spec.v2_0.parser.AdditionalPropertiesContext
with the right checking
```python
  if self._obj not in [None, {}]:
```

Once you finished, another issue would be raised, it seems there is cycle reference in their swagger.json.
You can skip that checking by loading this document in non-default way:
```python
  app = SwaggerApp.load(______url________)
  app.prepare(strict=False)
```
I'm not sure about the right way to handle cycle reference, so I will leave it un-fix this time. If you have any thought / more issues, please feel free to let me know.

**Comment by seanfarley** [comment] 2015-12-12 02:03
Thanks for the quick response! I am also unsure about the cyclic reference but don't see an easy way out. For reference, I work on the Bitbucket team and can ask my co-worker that wrote this for what to do. That will probably have to wait until next week.

**Comment by mission-liao** [comment] 2015-12-12 02:06
Actually, it should be fine on normal use case, except when you want to use the random inputs generator of pyswagger.

**Comment by seanfarley** [comment] 2015-12-12 02:12
Well, that's good news. I'll test it out this weekend see how it goes.

**Comment by mission-liao** [comment] 2015-12-12 03:05
Thanks, hope everything goes well. A version would be released after I fix( or workaround, :) ) what you find.

**Comment by mission-liao** [comment] 2015-12-30 12:54
This issue seems stalled, gonna provide a build before Friday and close it.

**Comment by seanfarley** [comment] 2015-12-30 18:35
Ah, sorry, forgot to reply that this worked for me! :+1:

**Comment by mission-liao** [comment] 2015-12-31 01:02
cool, a build would be release before new year's eve, :+1:

**Comment by mission-liao** [comment] 2015-12-31 12:51
A built error raised after submitting a change on VERSION, seems an CI env change.

**Closed** 2015-12-31 12:59 UTC
