### ISSUE TITLE
How to set different accept and content-type in the header when call the request

### ISSUE THREAD

**Issue by LouisZou** [mission-liao/pyswagger#61] opened 2016-01-27 08:28 UTC
I call the request and found the log like following:
pyswagger.core - INFO - request.header: {'Accept': 'application/json'}

But for my restful API, need the special accept and content-type such as "application/my+json",
so the request failed because of error media type.
how to send the correct type for my request.

**Comment by mission-liao** [comment] 2016-01-27 08:49
Hi, pyswagger can only produce request with content-type: application/json, an modification for content-type other than json is still ongoing [here](https://github.com/mission-liao/pyswagger/pull/49).

One thing needs to be clarified before going further: is "application/my+json" a special json, or just a special name in your service for json?

**Comment by LouisZou** [comment] 2016-01-29 06:46
Thanks mission-liao, the type "application/my+json"  is a special type in our restful service and the server will check the type of request.

I think I can do some customization for this issue by change the code "class SwaggerRequest(object)".

I think I can read the real type from the json file and I need only set this type into header and then send request to my restful api server.

**Comment by mission-liao** [comment] 2016-01-30 01:51
The problem is, the way to handle content type in pyswagger is static, and can't be pluggable, which means it can't things like "application/my+json".

A fix would be required for pyswagger to be extensible, One more thing to make sure @LouisZou , so "application/my+json" is actually a different name for json, which is nothing different from how we encode swagger primitives to json?

**Comment by LouisZou** [comment] 2016-02-02 03:17
Sure, the "application/my+json" is also a json type but special name in my restful server.
I can also deal with it as a normal json format.

**Comment by mission-liao** [comment] 2016-02-02 15:09
OK, I think that use case should be covered by that PR.

**Comment by LouisZou** [comment] 2016-02-04 09:17
Hi mission-liao, I found this issue is fixed with issue#49.
And now how can I use it with the newest pyswagger?
just like:
req, resp  = op(user='Tom')
req.mime = ("myjson", "myjson")
resp = client.request((req, resp),)

## analyze the resp to get response from http server.
is this correct?

**Comment by LouisZou** [comment] 2016-02-04 09:25
And sorry for I don't understand the sentence 
req, resp = op(user='Tom')
does this sentence will execute the method  op?
can I use it like "req, resp=op()"?
because I will decide how to set the parameter later such as,
op(body=mybody) or op(user='Tom').
in fact, my read code will be:
client.request(eval("op(" + tagUser +"='Tom'")) -- tagUser is a variable whose value is "user".

**Comment by mission-liao** [comment] 2016-02-05 03:37
The design of pyswagger to perform an Operation Object is to return a tuple of (SwaggerReqeust, SwaggerResponse). If you just use it in this form:
```python
client.request(op(user="Tom"))
```
The tuple of SwaggerRequest, SwaggerResponse is silently pass to client.request. If you need more customization, you need to pass them in this form
```python
req, resp = op(user="Tom")
req.mime .... # any customization
resp.xxxx

client.request((req, resp,)) # pass them as a tuple
```

The mime part is still under review, and would be merged to next release.

**Comment by LouisZou** [comment] 2016-02-05 06:20
Thanks mission-liao. 
for the req, resp, can I consider them as the meaning of the words.
Assume now my restful server need content-type is myjon1 in request and accept is myjon2 in response, so I will write:
req.mime("myjon1","")
resp.mime("","myjon2")
it this correct?

or:
req.mime("myjson1","myjson2")

**Comment by mission-liao** [comment] 2016-02-05 10:10
No, you can refer to that PR for more info.
```python
req.produce(...)
req.consume(...)
```

**Comment by mission-liao** [comment] 2016-02-16 08:40
This PR is merged in latest build.

**Comment by LouisZou** [comment] 2016-02-18 11:49
HI mission, I used the newest revision 0.8.18, when I call the request, it failed with the following message : 
Could not find codec for "myjson", => it is in the function marshall.

**Comment by LouisZou** [comment] 2016-02-18 12:01
I noticed the following code:
 +class MimeCodec:
+    def __init__(self):
+        self._codecs = {}
+        self.register('text/plain', PlainCodec())
+        jsonCodec = JsonCodec()
+        self.register('application/json', jsonCodec)
+        self.register('text/json', jsonCodec)

I have a new mime type in my definition file and I want to set this type to header and then send request to server.
for my curl command ,it like this:
curl --header {"Content-Type":"myjson", "Accept":"myjson"}

does need this mime to be registered just like above code?

**Comment by LouisZou** [comment] 2016-02-19 00:34
Addition:
in the revision 0.8.17, I can fix the code as the following and then I can use "my+json" as content-type and Accept in the header and then send request .

so I also think pyswagger can read the real mime-type for each operation from my definition file and then send request with them.

How can I realize this simply?

**Comment by mission-liao** [comment] 2016-02-19 02:02
Hi, the guy helped to implement that feature also provide a [guide](https://github.com/mission-liao/pyswagger/blob/master/docs/md/tutorial/mime.md) to register a customized codec. If that one doesn't solve your problem, please help to provide more details about what you want to do.

**Comment by LouisZou** [comment] 2016-02-19 08:13
Hi mission-liao, I write my program according to the guide code but the above error occurs.
And now I add the following code ,it can work.
in site-packages/pyswagger/primitives/codec.py
 6 class MimeCodec:
  7     def __init__(self):
...
13         self.register('application/my01+json', jsonCodec)
14         self.register('application/my02+json', jsonCodec)

so the method marshal know my mime type and then the request work well.

but about this issue. I think I don't need to marshal and unmashal my data according to my mime type. I only need to set the Content-Type and Accept in Header of Request.
And I think these types should be read from definition file by pyswagger because I specify the consume and produce in my operation.

what do you think?

**Comment by mission-liao** [comment] 2016-02-19 14:49
Hi, I will write a test sample for your case tomorrow. Besides that, I can't get your point for:

> don't need to marshal and unmashal my data according to my mime type

I can't get your point, any python primitives (dict, list) should be marshalled to some representative form in string when sending to servers.

**Comment by mission-liao** [comment] 2016-02-20 02:10
works with sample code:
```python
from pyswagger import SwaggerApp
from pyswagger.primitives import MimeCodec
from pyswagger.primitives.codec import JsonCodec

# init codecs
codecs = MimeCodec()
codecs.register('application/my01+json', JsonCodec)
codecs.register('application/my02+json', JsonCodec)

# init SwaggerApp with customized primitive factory
app = SwaggerApp.load('./swagger.json', mime_codec=codecs)
app.prepare()
op = app.s('/t').get

# make sure my01xxxxx in that 'op'
print op._mime_codec._codecs.keys() # expected ['application/my02+json', 'application/my01+json', 'application/json', 'text/plain', 'text/json']
```
with sample spec
```json
{
   "swagger":"2.0",
   "host":"http://test.com",
   "basePath":"/v1",
   "paths":{
      "/t":{
         "get":{
            "parameters":[
               {
                  "in":"body",
                  "name":"body",
                  "schema":{
                     "$ref":"#/definitions/MyRequest"
                  }
               }
            ],
            "responses":{
               "default":{
                  "description":"void"
               }
            }
         }
      }
   },
   "definitions":{
      "MyRequest":{
         "properties":{
            "units":{
               "additionalProperties":{
                  "format":"int32",
                  "type":"integer"
               }
            },
            "username":{
               "type":"string"
            }
         }
      }
   }
}
```

**Comment by LouisZou** [comment] 2016-02-22 01:06
Thanks mission.
before I add the register sentence in the codec.py, it work well.
that's meaning user can also call this method register in self's code.

I will fix my code.

**Comment by LouisZou** [comment] 2016-02-25 08:15
hi mission,
sorry for so late to test the code.
now i used the register code like above and I can print myjson1/2 with the code but the request failed with the exception:
Exception:unbound method marshal() must be called with JsonCodec instance as first argument (got Model instance instead)

**Comment by LouisZou** [comment] 2016-02-25 09:06
And in my source code 
`` 30         codecs.register('application/json',JsonCodec)
 31         codecs.register('application/myjson2', JsonCodec)
``
 line 30 is ok but line 32 failed with the above exception.

**Comment by LouisZou** [comment] 2016-02-25 09:12
Addition,
If I add the register code in the file primitives/codec.py:
  6 class MimeCodec:
  7     def __init__(self):
  ...
 13         self.register('application/myjson01', jsonCodec)
 14         self.register('application/myjson02', jsonCodec)

it work well

**Comment by mission-liao** [comment] 2016-02-25 11:55
Could you paste the full trace of that exception?

**Comment by WillaLuo** [comment] 2016-02-26 08:30
Hi mission, Here is the full exception.
File "/scratch/shuluo/swagger/swagger_sdk/compute-controlplane/virtualenv/lib/python2.6/site-packages/pyswagger/io.py", line 75, in _prepare_body
    return content_type, self.__op._mime_codec.marshal(content_type, body, _type=_type, _format=_format, name=name)
  File "/scratch/shuluo/swagger/swagger_sdk/compute-controlplane/virtualenv/lib/python2.6/site-packages/pyswagger/primitives/codec.py", line 29, in marshal
    return codec.marshal(value, **kwargs)
TypeError: unbound method marshal() must be called with JsonCodec instance as first argument (got Model instance instead)

It seems like there is something in this line:
app = SwaggerApp.load('./swagger.json', mime_codec=codecs)

**Comment by mission-liao** [comment] 2016-02-26 15:59
I guess some code in my sample is wrong, and would only failed when something really loaded.....
```python
"""
should be instance, not class
"""
codecs.register('application/json',JsonCodec)  # Wrong
codecs.register('application/myjson2', JsonCodec) # Wrong

"""
should work in this way
"""
jsonC = JsonCodec()
codecs.register('application/json',jsonC) 
codecs.register('application/myjson2', jsonC)
```

Sorry for my wrong sample.

**Comment by WillaLuo** [comment] 2016-02-27 02:23
Hi, mission, it works now. Thanks very much!

**Comment by mission-liao** [comment] 2016-03-09 16:23
It should be fine to close it now, please feel free to reopen it when things go wrong.

**Closed by mission-liao** 2016-03-09 16:23 UTC
